### PR TITLE
Remove hashtable

### LINKED ISSUE #1: Don't use already_seen hashtable when not following links
Hi,

as far as I can see the already_seen hashtable is only needed to prevent symlink loops. It adds to the memory consumption of async_find proportional to the number of directories. This can be a quite big amount of ram for large filesystems.

### PR DESCRIPTION
**Pull request by madroach**
To prevent loops it suffices to look at parent directories.
Therefore simply store device and inode together with each path component.
Due to memory sharing in lists memory requirement will be
O(max_depth + largest dir) instead of O(all dirs).
CPU usage is O(MIN(max_depth, PATH_MAX).

This also changes behavior in that several symlinks to the same directory
will be followed and the directory will be listed multiple times. This
matches the behaviour of posix find and is reasonable because otherwise a
directory (and its contents) might be listed via the symlink only, but not
via the original directory.

Note also that follow_links is false by default.
fixes #1.

### CODE REVIEW

**Comment by aalekseyev** [comment]
This PR also suppresses any errors when following a symlink, which is probably undesirable.

**Comment by aalekseyev** [comment]
@madroach Why are you doing the same check in handle_dirs and in stat? I'm assuming the check in `handle_dirs` is redundant.

**Comment by aalekseyev** [comment]
I reviewed the patch and changed it significantly:
https://github.com/janestreet/async_find/commit/1680c5141660a50343748f7de63265b6fe7e1cfc

@madroach, could you please sign the OCaml Core Suite Individual Contributor License Agreement (http://janestreet.github.io/contributing.html) so we're able to incorporate this change?

**Comment by madroach** [comment]
I don't own any patents and I don't claim any copyright over my code or your reworked code. Thanks for the review!
Do you still need this contributers license agreement signed?

**Comment by yminsky** [comment]
We do, I'm afraid. Sorry for the paperwork, bit it is pretty simple.

y

**Comment by madroach** [comment]
Done. Sorry for taking so long.

**Comment by madroach** [comment]
obsoleted by f1e52e682741558d1d104b55714b3d38f12625a1

**Comment by aalekseyev** [comment]
The result is the same, but It's "incorporated into" rather than "obsoleted". Thank you!

**Pull request closed without merging**
